# Generated by Django 4.1.7 on 2023-03-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.CharField(choices=[['zero', 'zero'], ['one', 'one'], ['two', 'two'], ['three', 'three'], ['four', 'four'], ['five', 'five'], ['six', 'six'], ['seven', 'seven'], ['eight', 'eight'], ['nine', 'nine']], max_length=10)),
                ('operator', models.CharField(choices=[['plus', 'plus'], ['minus', 'minus'], ['times', 'times'], ['divided_by', 'divided_by']], max_length=20)),
                ('operand2', models.CharField(choices=[['zero', 'zero'], ['one', 'one'], ['two', 'two'], ['three', 'three'], ['four', 'four'], ['five', 'five'], ['six', 'six'], ['seven', 'seven'], ['eight', 'eight'], ['nine', 'nine']], max_length=10)),
                ('output', models.IntegerField()),
            ],
        ),
    ]
